language: python

python:
  - 3.6
  - 3.7

install:
  - pip install pytest pytest-cov
  - pip install codecov
  - pip install numpy pandas
  - pip install .

script:
  - py.test --pytest-cov

after_success:
  - codecov

notifications:
  email: false